### ISSUE TITLE
MBUG-110 Typo in Calm Emotions Full Description

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#196]
Version number of the sheet
13.1.4+221130

Steps to reproduce
Make any spell sheet with calm emotions and mouse over the spell to make the full description come up

Description
Missing semicolon before "a creature can choose to fail this saving throw"

- Mormegil#0962
Verification: 0

**Comment by SheilaSardellaYJ** [comment]
Based on the information provided, it seems that there is an issue with the description of the "calm emotions" spell in a certain version (13.1.4+221130) of a spell sheet. Specifically, there is a missing semicolon before "a creature can choose to fail this saving throw."

The issue was reported by a user named Mormegil#0962 and has not yet been verified.

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979

Resolved - Fixed in v13.1.5
